apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: my-2048-game
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30080  # This is the NodePort you will use to access your service
  type: NodePort